services:
# -----------------------------------------------------------
# The web shop
#------------------------------------------------------------
  app:
    image: maven:3.8.3-openjdk-17
    container_name: webshop
    volumes: 
    - ./shop:/app
    working_dir: /app
    ports:
    - "8080:8080"
    command: /bin/sh -c "mvn clean package && java -jar target/shop-0.0.1-SNAPSHOT.jar"

# ------------------------------------------------------------
# Zookeeper - manages Kafka's distributed system
# ------------------------------------------------------------
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

# ------------------------------------------------------------
# Kafka
# ------------------------------------------------------------
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

# ------------------------------------------------------------
# Kafka Connect
# ------------------------------------------------------------
  connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kconnect
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/plugins
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
    ports:
      - "8083:8083"
    volumes:
      - ./plugins:/etc/kafka-connect/plugins

# ------------------------------------------------------------
# ApiCurio Registry
# ------------------------------------------------------------
  apicurio-registry:
    image: apicurio/apicurio-registry:3.0.6
    container_name: apicurio
    ports:
      - "8081:8080"
# ------------------------------------------------------------
# ApiCurio Registry UI
# ------------------------------------------------------------
  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:3.0.4
    container_name: apicurioui
    ports:
      - "8888:8080"
    environment:
      REGISTRY_API_URL: http://localhost:8081/apis/registry/v3
# ------------------------------------------------------------
# Kafdrop
# ------------------------------------------------------------
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka